#include "exception_ce.h"
#include <zend_exceptions.h>
#include "exception_arginfo.h"

zend_class_entry *php_temporal_exception_ce;

zend_class_entry *php_temporal_exception_date_time_conversion_ce;
zend_class_entry *php_temporal_exception_formatting_ce;
zend_class_entry *php_temporal_exception_parsing_ce;
zend_class_entry *php_temporal_exception_value_out_of_range_ce;
zend_class_entry *php_temporal_exception_unknown_time_zone_ce;

void php_temporal_register_exception_ce() {
	php_temporal_exception_ce = register_class_Temporal_TemporalException(zend_ce_exception);

	php_temporal_exception_date_time_conversion_ce = register_class_Temporal_Exception_DateTimeConversionException(php_temporal_exception_ce);
	php_temporal_exception_formatting_ce = register_class_Temporal_Exception_FormattingException(php_temporal_exception_ce);
	php_temporal_exception_parsing_ce = register_class_Temporal_Exception_ParsingException(php_temporal_exception_ce);
	php_temporal_exception_value_out_of_range_ce = register_class_Temporal_Exception_ValueOutOfRangeException(php_temporal_exception_ce);
	php_temporal_exception_unknown_time_zone_ce = register_class_Temporal_Exception_UnknownTimeZoneException(php_temporal_exception_ce);
}
